### ISSUE TITLE
Nodeyez project

### ISSUE THREAD

**Issue by thrillerxx** [vicariousdrama/nodeyez#114]
Hello Nodeyez,

Hope you're doing well! I'm Car, part of the [PlebLab hackerspace community](https://www.meetup.com/pleb-lab/events/294453547/). We're all about nurturing curiosity and supporting bitcoin lightning development and continuous learning; I am inquiring about Nodeyez project. Been trying to reach you via email but its not working? Do you have another means I could get in contact with you

**Comment by vicariousdrama** [comment]
Hi.  I have no inbound email support at this time. The best way to reach me is here as issues in GitHub, or via Nostr on my pubkey npub1yx6pjypd4r7qh2gysjhvjd9l2km6hnm4amdnjyjw3467fy05rf0qfp7kza identified with NIP-05 as vicariousdrama@nodeyez.com if you need to send a direct encrypted message.

**Comment by thrillerxx** [comment]
will do
